test_that("dots get turned to answers", {
  t1 <- etude2:::dots_to_learnr_answers("A", B=3, right_one="B")
  expect_equal(t1$item, c("A", "B"))
  expect_equal(t1$feedback, c("", "3"))
  expect_equal(t1$correct, c(FALSE, TRUE))
  t2 <- etude2:::dots_to_learnr_answers("A", "+B+"=3)
  expect_equal(t2$item, c("A", "B"))
  expect_equal(t2$feedback, c("", "3"))
  expect_equal(t2$correct, c(FALSE, TRUE))
  expect_error(etude2:::dots_to_learnr_answers("+A+", "+B+"=3))
  t4 <- etude2:::dots_to_learnr_answers("+A+", "B"=3, right_one="B", allow_multiple_correct = TRUE)
  expect_equal(t4$correct, c(TRUE, TRUE))
  t5 <- etude2:::dots_to_answers(1:4, right_one = 3)
  expect_equal(t5$correct, c(FALSE, FALSE, TRUE, FALSE))
})
