```{r context="server"}
library(learnr, quietly = TRUE)
library(gradethis, quietly = TRUE)
library(etude2, quietly = TRUE)
library(learnrhash, quietly = TRUE)

if (!exists(apps_state)) apps_state <- reactiveValues()

shiny_state <- shiny::eventReactive(input$get_state, {
  dplyr::bind_rows(reactiveValuesToList(apps_state))
})

current_state <- shiny::eventReactive(input$get_state, {
  All <- learnr:::get_objects(session)
  objs = learnr:::get_all_state_objects(session)
  objs = learnr:::submissions_from_state_objects(objs)
# Discard sandboxes without checking
  keepers <- rep(TRUE, length(objs))
  for(k in 1:length(objs)) {
    if (objs[[k]]$type == "exercise_submission") {
      if (!objs[[k]]$data$checked) {
        keepers[k] <- FALSE
      }
    }
  }
  
  return(objs[keepers])
})
current_state_report <- reactive({
  state_objs <- current_state()
  app_results <- shiny_state()
  
  save(state_objs, app_results, file="~/Downloads/state.rda")
  if (length(state_objs) == 0 && !inherits(app_results, "data.frame")) { 
    return(tibble(message="No submissions yet"))
  }
  condense <- function(item) {
    if (item$type == "exercise_submission") {
      tibble::tibble(id = item$id,
                     question = "codebox",
                     answer = item$data$code,
                     time = format(Sys.time(), tz="GMT", usetz=TRUE),
                     correct = if (item$data$checked) item$data$feedback$correct else FALSE,
                     attempts = 999,
                     history=NA
      )
    } else { # question submission
      tibble::tibble(id=item$id,
                     question  = substr(item$data$question, 0, 20),
                     answer=item$data$answer,
                     time = format(item$data$time, tz="GMT", usetz=TRUE),
                     correct = ifelse(item$data$is_essay,
                                      NA, item$data$correct),
                     attempts = length(item$data$history)/2,
                     history = paste0(unlist(item$data$history),collapse=":::")
      )
    }
  }
  
  For_report <- lapply(state_objs, condense) %>%
    dplyr::bind_rows()
  
  if (inherits(app_results, "data.frame"))
    For_report <- bind_rows(For_report, app_results)
 

  if (exists("document_roster")) {
    For_report <- For_report %>%
      dplyr::full_join(document_roster, by = "id")
  }

  For_report %>%
    dplyr::mutate(document = etude2::etude_document_name()) %>%
    dplyr::arrange(id)

})
output$current_answers <- renderTable({
  current_state_report() %>%
    dplyr::select(-history)})


output$hash_output <- renderText({
   paste(names(input), collapse="\n")
  
 Res <- current_state_report() %>% 
   dplyr::filter(!is.na(answer)) %>%
    learnrhash::encode_obj()
 

 Res
 
})
```

```{r state, echo=FALSE}
shiny::actionButton("get_state", "Refresh summary of responses")
learnrhash:::wrapped_verbatim_text_output("hash_output", TRUE)
shiny::tableOutput("current_answers")
shiny::plotOutput("bogus") # just to provide some space 
      # before the learnr advance/retreat buttons.
```

